dist: xenial
language: python
services:
  - docker

install:
  - pip install -e .
  - pip install -r requirements_test.txt

script: pytest opsdroid_homeassistant --cov --cov-report term

after_success: codecov

jobs:
  fast_finish: true
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - stage: deploy
      script: skip     # usually you do not want to rerun any tests
      python: "3.7"
      deploy:
        provider: pypi
        user: $PYPI_USER
        password: $PYPI_PASSWORD
        skip_cleanup: true
        on:
          tags: true
          repo: opsdroid/opsdroid-homeassistant
